name: Crashlytics Test 2

on: workflow_dispatch

jobs:
  crashlytics_test_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          check-latest: true
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: flutter-fvm-config-action
      - uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          flutter-version: ${{ steps.flutter-fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.flutter-fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - name: Build
        run: |
          flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols
      - name: Upload symbol files to Crashlytics
        uses: w9jds/firebase-action@v13.15.0
        with:
          args: crashlytics:symbols:upload --app=${{ secrets.FIREBASE_APP_ID }} build/app/outputs/symbols
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_CREDENTIAL_FILE_BASE64 }}