name: Crashlytics Test

on: workflow_dispatch

jobs:
  crashlytics_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          check-latest: true
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: flutter-fvm-config-action
      - uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          flutter-version: ${{ steps.flutter-fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.flutter-fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - name: Build
        run: |
          flutter build apk --release --obfuscate --split-debug-info=outputs
      - name: Install firebase CLI
        run: curl -sL https://firebase.tools | bash
      - name: export GOOGLE_APPLICATION_CREDENTIALS_JSON
        run: echo ${{ secrets.FIREBASE_CREDENTIAL_FILE_BASE64 }} > /tmp/google_application_credentials.json
      - name: Upload symbols to firebase crashlytics
        run: firebase crashlytics:symbols:upload --app=${{ secrets.FIREBASE_APP_ID }} outputs
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google_application_credentials.json